import {
  User,
  NetworkNode,
  NetworkConnection,
  SecurityAlert,
  NewsItem,
  ChatMessage,
  ChatChannel,
  Participant,
  AuditLog,
  RegionZone,
  IntelligenceReport,
  InvoiceItem,
  NotificationItem,
} from './types';

export const INITIAL_CURRENT_USER: User = {
  id: 'usr-syc-001',
  name: 'Marcus Vance',
  email: 'm.vance@sycron.net',
  phone: '+55 11 98421-9900',
  role: 'Analyst',
  region: 'São Paulo — Centro / Paulista',
  plan: 'PRO',
  joinedDate: '12/03/2025',
  nodesCount: 38,
  confirmedReportsCount: 142,
  twoFactorEnabled: true,
};

export const INITIAL_INVOICES: InvoiceItem[] = [
  { id: 'INV-2026-0891', date: '01/08/2026', amount: 'R$ 189,00', plan: 'SYCRON Analyst PRO', status: 'PAGO', method: 'Cartão Corporativo •••• 8842' },
  { id: 'INV-2026-0743', date: '01/07/2026', amount: 'R$ 189,00', plan: 'SYCRON Analyst PRO', status: 'PAGO', method: 'Cartão Corporativo •••• 8842' },
  { id: 'INV-2026-0612', date: '01/06/2026', amount: 'R$ 189,00', plan: 'SYCRON Analyst PRO', status: 'PAGO', method: 'Cartão Corporativo •••• 8842' },
];

export const INITIAL_REGIONS: RegionZone[] = [
  {
    id: 'reg-01',
    name: 'Setor Central',
    code: 'SEC-01-CTR',
    coordinates: { x: 380, y: 280, lat: -23.5505, lng: -46.6333 },
    threatLevel: 'HIGH',
    activeAlertsCount: 7,
    activeAnalysts: 14,
    description: 'Alta densidade de infraestrutura bancária, servidores corporativos e backbones de telecomunicações.',
    incidentsHistory: [12, 19, 15, 24, 28, 22, 31],
  },
  {
    id: 'reg-02',
    name: 'Polo Tecnológico Berrini',
    code: 'SEC-02-BRN',
    coordinates: { x: 310, y: 390, lat: -23.6015, lng: -46.6975 },
    threatLevel: 'MEDIUM',
    activeAlertsCount: 4,
    activeAnalysts: 9,
    description: 'Concentração de sedes de fintechs, data centers privados e empresas multinacionais de software.',
    incidentsHistory: [8, 11, 9, 14, 16, 12, 15],
  },
  {
    id: 'reg-03',
    name: 'Eixo Paulista',
    code: 'SEC-03-PLT',
    coordinates: { x: 360, y: 320, lat: -23.5614, lng: -46.6558 },
    threatLevel: 'CRITICAL',
    activeAlertsCount: 11,
    activeAnalysts: 22,
    description: 'Ponto crítico de tráfego de dados sensíveis, consulados, hospitais e redes sem fio metropolitanas.',
    incidentsHistory: [21, 24, 30, 28, 35, 42, 49],
  },
  {
    id: 'reg-04',
    name: 'Distrito Industrial Norte',
    code: 'SEC-04-IND',
    coordinates: { x: 440, y: 160, lat: -23.5012, lng: -46.6120 },
    threatLevel: 'LOW',
    activeAlertsCount: 2,
    activeAnalysts: 6,
    description: 'Redes SCADA e sistemas de controle industrial (OT). Monitoramento de telemetria e sensores IoT.',
    incidentsHistory: [4, 5, 3, 6, 4, 7, 5],
  },
  {
    id: 'reg-05',
    name: 'Hub Logístico Portuário',
    code: 'SEC-05-LOG',
    coordinates: { x: 520, y: 440, lat: -23.9618, lng: -46.3322 },
    threatLevel: 'MEDIUM',
    activeAlertsCount: 5,
    activeAnalysts: 8,
    description: 'Sistemas alfandegários, rastreamento de cargas críticas e conexões de cabos submarinos.',
    incidentsHistory: [9, 14, 12, 18, 15, 17, 20],
  },
  {
    id: 'reg-06',
    name: 'Gateway Internacional',
    code: 'SEC-06-INT',
    coordinates: { x: 220, y: 180, lat: -23.4356, lng: -46.4731 },
    threatLevel: 'HIGH',
    activeAlertsCount: 8,
    activeAnalysts: 11,
    description: 'Interconexões internacionais, terminais aéreos e roteamento BGP de tráfego transfronteiriço.',
    incidentsHistory: [14, 16, 19, 22, 25, 29, 33],
  },
];

export const INITIAL_NODES: NetworkNode[] = [
  {
    id: 'node-root-01',
    title: 'NÚCLEO REGIONAL: Eixo Paulista',
    category: 'REGION',
    location: 'Av. Paulista, Setor 03',
    coordinates: { x: 450, y: 300, lat: -23.5614, lng: -46.6558 },
    date: '19/08/2026',
    time: '04:30:12',
    authorId: 'usr-syc-001',
    authorName: 'Marcus Vance',
    priority: 'CRITICAL',
    description: 'Hub central de monitoramento de tráfego de dados e infraestrutura crítica do corredor Paulista.',
    confirmations: 42,
    tags: ['NÚCLEO', 'BACKBONE', 'SETOR-03'],
    attachments: [
      { id: 'att-1', name: 'topologia_rede_paulista.json', size: '2.4 MB', type: 'JSON' },
      { id: 'att-2', name: 'relatorio_espectro_rf.pdf', size: '5.1 MB', type: 'PDF' },
    ],
    comments: [
      {
        id: 'c-1',
        authorId: 'usr-002',
        authorName: 'Dra. Helena Rossi',
        authorRole: 'Analyst',
        content: 'Tráfego anômalo detectado no switch de borda L3 às 03:15.',
        timestamp: '19/08/2026 04:45',
      },
    ],
    x: 480,
    y: 320,
    isMainBlock: true,
  },
  {
    id: 'node-alert-01',
    title: 'ALERTA: Credential Stuffing em VPN Gateway',
    category: 'ALERT',
    location: 'Av. Paulista, 1374 - Edifício Corporativo',
    coordinates: { x: 260, y: 190, lat: -23.5620, lng: -46.6540 },
    date: '19/08/2026',
    time: '04:12:00',
    authorId: 'usr-003',
    authorName: 'Alexandre Prado',
    priority: 'CRITICAL',
    description: 'Tentativa massiva de força bruta distribuída (3.400 req/s) visando concentrador VPN Fortinet v7.2.',
    confirmations: 28,
    tags: ['BRUTE-FORCE', 'VPN', 'BOTNET', 'CVE-2024-21762'],
    attachments: [
      { id: 'att-3', name: 'auth_failure_dump.log', size: '8.7 MB', type: 'LOG' },
      { id: 'att-4', name: 'iocs_ips_origem.txt', size: '420 KB', type: 'IOC' },
    ],
    comments: [
      {
        id: 'c-2',
        authorId: 'usr-syc-001',
        authorName: 'Marcus Vance',
        authorRole: 'Analyst',
        content: 'IPs de origem mapeados para ASN 4837 e ASN 4134. Regras de mitigação WAF aplicadas.',
        timestamp: '19/08/2026 04:50',
      },
    ],
    x: 230,
    y: 160,
    linkedEntityId: 'alt-001',
  },
  {
    id: 'node-part-01',
    title: 'PARTICIPANTE: Equipe CSIRT Financeiro',
    category: 'PARTICIPANT',
    location: 'Centro Integrado de Operações (SOC)',
    coordinates: { x: 740, y: 190, lat: -23.5590, lng: -46.6580 },
    date: '19/08/2026',
    time: '03:55:00',
    authorId: 'usr-004',
    authorName: 'Carla Mendez',
    priority: 'HIGH',
    description: 'Time de resposta a incidentes do consórcio bancário atuando na contenção ativa de tokens expostos.',
    confirmations: 19,
    tags: ['SOC', 'CSIRT', 'FINANCEIRO', 'RESPOSTA-RAPIDA'],
    attachments: [],
    comments: [],
    x: 740,
    y: 170,
  },
  {
    id: 'node-news-01',
    title: 'NOTÍCIA: Vazamento de Hashes NTLM Detectado em Fórum',
    category: 'NEWS',
    location: 'Darkweb / Fórum Especializado',
    coordinates: { x: 760, y: 470, lat: -23.5650, lng: -46.6510 },
    date: '19/08/2026',
    time: '02:40:00',
    authorId: 'usr-005',
    authorName: 'Rafael Tavares',
    priority: 'HIGH',
    description: 'Base de dados contendo 14.800 credenciais corporativas de domínio .br anunciada para negociação.',
    confirmations: 34,
    tags: ['DATA-BREACH', 'NTLM', 'DARKWEB', 'CREDENCIAIS'],
    attachments: [
      { id: 'att-5', name: 'sample_hashes_redacted.txt', size: '1.1 MB', type: 'IOC' },
    ],
    comments: [
      {
        id: 'c-3',
        authorId: 'usr-006',
        authorName: 'Felipe Duarte',
        authorRole: 'Moderator',
        content: 'Verificado. Cruzamento de domínios corporativos afeta 4 empresas da região Centro/Paulista.',
        timestamp: '19/08/2026 03:10',
      },
    ],
    x: 760,
    y: 470,
    linkedEntityId: 'news-001',
  },
  {
    id: 'node-inc-01',
    title: 'OCORRÊNCIA: Rogue AP Evil Twin Disseminado',
    category: 'INCIDENT',
    location: 'Alameda Santos x R. Augusta',
    coordinates: { x: 210, y: 450, lat: -23.5580, lng: -46.6620 },
    date: '19/08/2026',
    time: '03:15:22',
    authorId: 'usr-syc-001',
    authorName: 'Marcus Vance',
    priority: 'MEDIUM',
    description: 'Ponto de acesso wireless clonando SSID de rede corporativa segura com portal captivo forjado.',
    confirmations: 16,
    tags: ['EVIL-TWIN', 'WIFI-ROGUE', 'MAN-IN-THE-MIDDLE'],
    attachments: [
      { id: 'att-6', name: 'bssid_beacon_analysis.pcap', size: '14.2 MB', type: 'PCAP' },
    ],
    comments: [],
    x: 210,
    y: 460,
    linkedEntityId: 'alt-003',
  },
  {
    id: 'node-info-01',
    title: 'INFORMAÇÃO: Vetor C2 via DNS Tunneling',
    category: 'INFORMATION',
    location: 'Servidor DNS Recursivo Local',
    coordinates: { x: 480, y: 600, lat: -23.5630, lng: -46.6570 },
    date: '19/08/2026',
    time: '04:40:10',
    authorId: 'usr-002',
    authorName: 'Dra. Helena Rossi',
    priority: 'HIGH',
    description: 'Requisições TXT anômalas com alta entropia decodificadas como payloads de exfiltração de dados.',
    confirmations: 22,
    tags: ['DNS-TUNNELING', 'C2', 'EXFILTRAÇÃO', 'IOC'],
    attachments: [
      { id: 'att-7', name: 'dns_entropy_chart.csv', size: '3.8 MB', type: 'DATA' },
    ],
    comments: [],
    x: 480,
    y: 600,
  },
  {
    id: 'node-info-02',
    title: 'EVIDÊNCIA: Certificado TLS Autoassinado Suspeito',
    category: 'INFORMATION',
    location: 'IP 185.220.101.5',
    coordinates: { x: 120, y: 310, lat: -23.5600, lng: -46.6500 },
    date: '19/08/2026',
    time: '05:01:45',
    authorId: 'usr-007',
    authorName: 'Gabriel Siqueira',
    priority: 'LOW',
    description: 'Impressão digital SHA-256 vinculada a campanhas anteriores do grupo Lazarus associadas a phishing.',
    confirmations: 9,
    tags: ['TLS-FINGERPRINT', 'JA3', 'LAZARUS', 'THREAT-INTEL'],
    attachments: [],
    comments: [],
    x: 100,
    y: 310,
  },
];

export const INITIAL_CONNECTIONS: NetworkConnection[] = [
  { id: 'conn-1', sourceId: 'node-root-01', targetId: 'node-alert-01', label: 'Incidente Ativo', type: 'DIRECT' },
  { id: 'conn-2', sourceId: 'node-root-01', targetId: 'node-part-01', label: 'Alocação CSIRT', type: 'CORRELATED' },
  { id: 'conn-3', sourceId: 'node-root-01', targetId: 'node-news-01', label: 'Correlação de Inteligência', type: 'INVESTIGATION' },
  { id: 'conn-4', sourceId: 'node-root-01', targetId: 'node-inc-01', label: 'Vetor Físico/Sem Fio', type: 'GEOGRAPHIC' },
  { id: 'conn-5', sourceId: 'node-root-01', targetId: 'node-info-01', label: 'Telemetria DNS', type: 'DIRECT' },
  { id: 'conn-6', sourceId: 'node-alert-01', targetId: 'node-info-02', label: 'Infraestrutura Cruzada', type: 'INVESTIGATION' },
  { id: 'conn-7', sourceId: 'node-alert-01', targetId: 'node-news-01', label: 'Base de Hashes Coincidente', type: 'CORRELATED' },
  { id: 'conn-8', sourceId: 'node-inc-01', targetId: 'node-info-01', label: 'Comunicação Exfiltrada', type: 'DIRECT' },
];

export const INITIAL_ALERTS: SecurityAlert[] = [
  {
    id: 'alt-001',
    title: 'Tentativa massiva de Credential Stuffing em VPN Gateway',
    type: 'Incidente digital',
    location: 'Av. Paulista, 1374 — Bela Vista',
    coordinates: { x: 360, y: 320, lat: -23.5620, lng: -46.6540 },
    date: '19/08/2026',
    time: '04:12',
    description: 'Concentrador VPN recebendo mais de 3.400 requisições/segundo oriundas de botnets residenciais. Múltiplas contas corporativas sofreram lockout.',
    priority: 'CRITICAL',
    author: 'Alexandre Prado',
    authorId: 'usr-003',
    authorRole: 'Analyst',
    status: 'INVESTIGATING',
    confirmations: 28,
    userConfirmed: true,
    reportedCount: 0,
    linkedNodeId: 'node-alert-01',
    evidenceCount: 4,
    isOfficial: true,
  },
  {
    id: 'alt-002',
    title: 'Dispositivo Rogue com Firmware Modificado em Ponto de Troca de Tráfego',
    type: 'Vulnerabilidade',
    location: 'Rua do Paraíso, 300 — Centro',
    coordinates: { x: 380, y: 280, lat: -23.5710, lng: -46.6430 },
    date: '19/08/2026',
    time: '03:45',
    description: 'Identificado switch não catalogado emitindo pacotes LLDP com vendor ID anômalo no rack 14B da operadora de trânsito IP.',
    priority: 'CRITICAL',
    author: 'Dra. Helena Rossi',
    authorId: 'usr-002',
    authorRole: 'Analyst',
    status: 'OPEN',
    confirmations: 31,
    userConfirmed: false,
    reportedCount: 0,
    evidenceCount: 3,
    isOfficial: false,
  },
  {
    id: 'alt-003',
    title: 'Rede Wi-Fi Falsa (Evil Twin) Coletando Credenciais de Visitantes',
    type: 'Atividade suspeita',
    location: 'Alameda Santos, 980 — Jardins',
    coordinates: { x: 350, y: 330, lat: -23.5680, lng: -46.6590 },
    date: '19/08/2026',
    time: '03:15',
    description: 'Ponto de acesso com beacon forjado de rede corporativa de coworking interceptando tráfego HTTP e forçando download de certificado raiz.',
    priority: 'HIGH',
    author: 'Marcus Vance',
    authorId: 'usr-syc-001',
    authorRole: 'Analyst',
    status: 'CONFIRMED',
    confirmations: 16,
    userConfirmed: true,
    reportedCount: 0,
    linkedNodeId: 'node-inc-01',
    evidenceCount: 2,
    isOfficial: true,
  },
  {
    id: 'alt-004',
    title: 'Campanha de Spear-Phishing direcionada ao Setor Financeiro',
    type: 'Fraude',
    location: 'Av. Brigadeiro Faria Lima, 3400 — Itaim Bibi',
    coordinates: { x: 310, y: 390, lat: -23.5870, lng: -46.6820 },
    date: '19/08/2026',
    time: '02:30',
    description: 'E-mails simulando notificações judiciais com anexos .ISO contendo malware loader assinado com certificado revogado.',
    priority: 'HIGH',
    author: 'Carla Mendez',
    authorId: 'usr-004',
    authorRole: 'Contributor',
    status: 'INVESTIGATING',
    confirmations: 24,
    userConfirmed: false,
    reportedCount: 1,
    evidenceCount: 5,
    isOfficial: false,
  },
  {
    id: 'alt-005',
    title: 'Exfiltração de Telemetria de Sensores IoT em Planta Industrial',
    type: 'Incidente digital',
    location: 'Vila Maria, 1200 — Distrito Norte',
    coordinates: { x: 440, y: 160, lat: -23.5012, lng: -46.6120 },
    date: '19/08/2026',
    time: '01:50',
    description: 'Comunicação contínua em porta não padronizada 8883 (MQTT criptografado) direcionada para VPS hospedado em Frankfurt.',
    priority: 'MEDIUM',
    author: 'Thiago Moura',
    authorId: 'usr-008',
    authorRole: 'Analyst',
    status: 'INVESTIGATING',
    confirmations: 12,
    userConfirmed: false,
    reportedCount: 0,
    evidenceCount: 1,
    isOfficial: true,
  },
  {
    id: 'alt-006',
    title: 'Tentativa de Escalação de Privilégio em Controladora de Acesso Físico',
    type: 'Ameaça',
    location: 'Rua Bela Cintra, 800 — Consolação',
    coordinates: { x: 340, y: 300, lat: -23.5530, lng: -46.6610 },
    date: '18/08/2026',
    time: '23:14',
    description: 'Leitora biométrica registrou 45 comandos de backdoor por interface serial RS-485 durante o plantão noturno.',
    priority: 'MEDIUM',
    author: 'Gabriel Siqueira',
    authorId: 'usr-007',
    authorRole: 'User',
    status: 'RESOLVED',
    confirmations: 18,
    userConfirmed: true,
    reportedCount: 0,
    evidenceCount: 2,
    isOfficial: false,
  },
  {
    id: 'alt-007',
    title: 'Vazamento de Chaves de API em Repositório Público de Terceiro',
    type: 'Vulnerabilidade',
    location: 'Polo Berrini, Rua Quintana — Brooklin',
    coordinates: { x: 315, y: 400, lat: -23.6050, lng: -46.6940 },
    date: '18/08/2026',
    time: '21:05',
    description: 'Chaves de produção da infraestrutura AWS e credenciais de banco PostgreSQL expostas em commit público.',
    priority: 'RESOLVED',
    author: 'Rafael Tavares',
    authorId: 'usr-005',
    authorRole: 'Analyst',
    status: 'RESOLVED',
    confirmations: 45,
    userConfirmed: true,
    reportedCount: 0,
    evidenceCount: 6,
    isOfficial: true,
  },
];

export const INITIAL_NEWS: NewsItem[] = [
  {
    id: 'news-001',
    title: 'Análise de Inteligência: Nova Variante de Ransomware foca em Infraestruturas Críticas',
    content: 'O laboratório de ameaças da SYCRON identificou um vetor de infecção utilizando executáveis disfarçados de atualizações de drivers SCADA. As cargas utilizam criptografia híbrida ChaCha20-Poly1305 com chave pública embutida, impedindo decodificação sem a chave privada dos atacantes.',
    location: 'São Paulo / Região Metropolitana',
    category: 'Threat Intelligence',
    author: 'Marcus Vance',
    authorId: 'usr-syc-001',
    authorRole: 'Analyst',
    date: '19/08/2026',
    time: '04:55',
    confirmations: 56,
    userConfirmed: true,
    saved: true,
    comments: [
      {
        id: 'nc-1',
        author: 'Dra. Helena Rossi',
        role: 'Analyst',
        text: 'Regras YARA para detecção dos binários já adicionadas ao feed de IOCs.',
        time: '19/08/2026 05:10',
      },
      {
        id: 'nc-2',
        author: 'Felipe Duarte',
        role: 'Moderator',
        text: 'Publicação revisada e certificada conforme o protocolo de inteligência nível 3.',
        time: '19/08/2026 05:18',
      },
    ],
    linkedNodeId: 'node-news-01',
  },
  {
    id: 'news-002',
    title: 'Alerta Coletivo: Ataques de BGP Hijacking interceptam tráfego de servidores DNS governamentais',
    content: 'Análise de telemetria de roteamento indica que múltiplos ASNs anunciaram prefixos IP ilegítimos durante janela de 18 minutos na madrugada. Parte do tráfego foi redirecionada para nós de interceptação antes do restabelecimento.',
    location: 'Setor Central / Telecom',
    category: 'Network Security',
    author: 'Alexandre Prado',
    authorId: 'usr-003',
    authorRole: 'Analyst',
    date: '19/08/2026',
    time: '03:30',
    confirmations: 43,
    userConfirmed: false,
    saved: false,
    comments: [
      {
        id: 'nc-3',
        author: 'Carla Mendez',
        role: 'Contributor',
        text: 'Adoção obrigatória de RPKI Route Origin Validation (ROV) teria prevenido o sequestro.',
        time: '19/08/2026 03:45',
      },
    ],
  },
  {
    id: 'news-003',
    title: 'Relatório Setorial: Evolução de Ameaças Físico-Digitais no Corredor Financeiro',
    content: 'Consolidado mensal aponta aumento de 34% em ataques combinados (engenharia social presencial + implante de dispositivos de hardware em pontos de rede expostos) em agências e escritórios de investimento.',
    location: 'Av. Paulista & Faria Lima',
    category: 'Relatório Mensal',
    author: 'Dra. Helena Rossi',
    authorId: 'usr-002',
    authorRole: 'Analyst',
    date: '18/08/2026',
    time: '20:15',
    confirmations: 89,
    userConfirmed: true,
    saved: true,
    comments: [],
  },
];

export const INITIAL_CHAT_MESSAGES: Record<string, ChatMessage[]> = {
  'chan-01': [
    {
      id: 'msg-1',
      channelId: 'chan-01',
      authorId: 'usr-003',
      authorName: 'Alexandre Prado',
      authorRole: 'Analyst',
      content: 'Identificamos rajadas de tráfego SYN flood sincronizadas com tentativas de autenticação VPN no Setor Paulista.',
      timestamp: '04:30',
    },
    {
      id: 'msg-2',
      channelId: 'chan-01',
      authorId: 'usr-002',
      authorName: 'Dra. Helena Rossi',
      authorRole: 'Analyst',
      content: 'Confirmado. A telemetria DNS aponta queries para domínios DGA recém-registrados na TLD .top.',
      timestamp: '04:42',
      pinned: true,
    },
    {
      id: 'msg-3',
      channelId: 'chan-01',
      authorId: 'usr-syc-001',
      authorName: 'Marcus Vance',
      authorRole: 'Analyst',
      content: 'Criei um nó de investigação na Network correlacionando o gateway com a base de dados do fórum.',
      timestamp: '05:01',
      location: 'Av. Paulista, 1374',
      linkedNodeId: 'node-alert-01',
    },
    {
      id: 'msg-4',
      channelId: 'chan-01',
      authorId: 'usr-006',
      authorName: 'Felipe Duarte',
      authorRole: 'Moderator',
      content: 'Alerta #ALT-001 validado e promovido para status de prioridade crítica na rede pública.',
      timestamp: '05:08',
    },
  ],
  'chan-02': [
    {
      id: 'msg-201',
      channelId: 'chan-02',
      authorId: 'usr-002',
      authorName: 'Dra. Helena Rossi',
      authorRole: 'Analyst',
      content: 'Equipe de campo reportou apreensão de equipamento passivo de sniffing próximo à Alameda Santos.',
      timestamp: '04:10',
    },
    {
      id: 'msg-202',
      channelId: 'chan-02',
      authorId: 'usr-syc-001',
      authorName: 'Marcus Vance',
      authorRole: 'Analyst',
      content: 'Estamos extraindo o firmware flash do dispositivo agora. PCAP será anexado ao nó da ocorrência.',
      timestamp: '04:35',
    },
  ],
  'chan-03': [
    {
      id: 'msg-301',
      channelId: 'chan-03',
      authorId: 'usr-003',
      authorName: 'Alexandre Prado',
      authorRole: 'Analyst',
      content: 'Lista de 4.100 IPs maliciosos adicionada à blacklist perimetral dos firewalls.',
      timestamp: '04:46',
      pinned: true,
    },
  ],
  'chan-04': [
    {
      id: 'msg-401',
      channelId: 'chan-04',
      authorId: 'usr-002',
      authorName: 'Dra. Helena Rossi',
      authorRole: 'Analyst',
      content: 'Marcus, você conseguiu validar a assinatura JA3 do payload que vimos no túnel DNS?',
      timestamp: '03:50',
    },
    {
      id: 'msg-402',
      channelId: 'chan-04',
      authorId: 'usr-syc-001',
      authorName: 'Marcus Vance',
      authorRole: 'Analyst',
      content: 'Sim, bateu com o nó de inteligência que o Gabriel subiu. Confirmando o hash do dump de tráfego DNS.',
      timestamp: '04:15',
    },
  ],
  'chan-05': [
    {
      id: 'msg-501',
      channelId: 'chan-05',
      authorId: 'usr-005',
      authorName: 'Rafael Tavares',
      authorRole: 'Analyst',
      content: 'Nova conexão criada com o fórum de credenciais expostas na teia de dados.',
      timestamp: '03:22',
    },
  ],
};

export const INITIAL_CHANNELS: ChatChannel[] = [
  {
    id: 'chan-01',
    name: 'Operações Gerais #intel-global',
    type: 'DIRECT',
    description: 'Canal principal de coordenação de inteligência e alertas de nível prioritário.',
    participantsCount: 84,
    unreadCount: 3,
    messages: INITIAL_CHAT_MESSAGES['chan-01'],
  },
  {
    id: 'chan-02',
    name: 'Região Paulista & Centro',
    type: 'REGION',
    description: 'Discussões focadas nas ocorrências das zonas Centro, Paulista e Berrini.',
    participantsCount: 36,
    unreadCount: 0,
    messages: INITIAL_CHAT_MESSAGES['chan-02'],
  },
  {
    id: 'chan-03',
    name: 'Incidente #ALT-001 (Credential Stuffing)',
    type: 'INCIDENT',
    description: 'Canal de crise dedicado à contenção e análise de IPs de ataque ao gateway VPN.',
    participantsCount: 12,
    unreadCount: 1,
    messages: INITIAL_CHAT_MESSAGES['chan-03'],
    linkedEntityId: 'alt-001',
  },
  {
    id: 'chan-04',
    name: 'Dra. Helena Rossi',
    type: 'DIRECT',
    description: 'Analista Sênior de Ameaças Cibernéticas & Infraestrutura Crítica',
    participantsCount: 2,
    unreadCount: 0,
    messages: INITIAL_CHAT_MESSAGES['chan-04'],
  },
  {
    id: 'chan-05',
    name: 'Teia de Inteligência [Node Paulista]',
    type: 'NODE',
    description: 'Discussão técnica vinculada ao bloco de dados regional.',
    participantsCount: 18,
    unreadCount: 0,
    messages: INITIAL_CHAT_MESSAGES['chan-05'],
    linkedEntityId: 'node-root-01',
  },
];

export const INITIAL_PARTICIPANTS: Participant[] = [
  {
    id: 'usr-syc-001',
    name: 'Marcus Vance',
    email: 'm.vance@sycron.net',
    role: 'Analyst',
    status: 'ONLINE',
    region: 'Eixo Paulista / Centro',
    bio: 'Especialista em Threat Hunting, análise de tráfego de rede e resposta a incidentes críticos.',
    specialties: ['Network Forensics', 'Threat Hunting', 'Malware Triage'],
    reputationScore: 98,
    contributionsCount: 42,
    verifiedAlertsCount: 38,
    joinedDate: '12/03/2025',
  },
  {
    id: 'usr-002',
    name: 'Dra. Helena Rossi',
    email: 'h.rossi@sycron.net',
    role: 'Analyst',
    status: 'ONLINE',
    region: 'Setor Central',
    bio: 'Doutora em Criptografia e Segurança de Infraestruturas Críticas. Líder de correlação de sinais.',
    specialties: ['Applied Cryptography', 'SCADA Security', 'Zero-Day Research'],
    reputationScore: 99,
    contributionsCount: 110,
    verifiedAlertsCount: 74,
    joinedDate: '08/01/2025',
  },
  {
    id: 'usr-003',
    name: 'Alexandre Prado',
    email: 'a.prado@sycron.net',
    role: 'Analyst',
    status: 'BUSY',
    region: 'Polo Berrini',
    bio: 'Engenheiro de Defesa Perimetral e especialista em detecção de campanhas de botnets e DDoS.',
    specialties: ['Perimeter Defense', 'DDoS Mitigation', 'BGP Security'],
    reputationScore: 95,
    contributionsCount: 67,
    verifiedAlertsCount: 52,
    joinedDate: '19/04/2025',
  },
  {
    id: 'usr-004',
    name: 'Carla Mendez',
    email: 'c.mendez@csirt-fin.org',
    role: 'Contributor',
    status: 'ONLINE',
    region: 'Centro Financeiro',
    bio: 'Analista sênior de CSIRT setorial focada em fraudes financeiras e engenharia social avançada.',
    specialties: ['Financial Fraud', 'OSINT', 'Phishing Analysis'],
    reputationScore: 92,
    contributionsCount: 31,
    verifiedAlertsCount: 29,
    joinedDate: '02/06/2025',
  },
  {
    id: 'usr-005',
    name: 'Rafael Tavares',
    email: 'r.tavares@intel-lab.io',
    role: 'Analyst',
    status: 'BUSY',
    region: 'Gateway Internacional',
    bio: 'Investigador de cibercrime, monitoramento de canais da darkweb e vazamento de bases de dados.',
    specialties: ['Darkweb Monitoring', 'Breach Intelligence', 'IOC Enrichment'],
    reputationScore: 96,
    contributionsCount: 58,
    verifiedAlertsCount: 44,
    joinedDate: '15/05/2025',
  },
  {
    id: 'usr-006',
    name: 'Felipe Duarte',
    email: 'f.duarte@sycron.net',
    role: 'Moderator',
    status: 'ONLINE',
    region: 'Geral / Supervisão',
    bio: 'Auditor de integridade de dados e moderação de evidências colaborativas da plataforma SYCRON.',
    specialties: ['Intelligence Moderation', 'Evidence Audit', 'Compliance'],
    reputationScore: 100,
    contributionsCount: 134,
    verifiedAlertsCount: 91,
    joinedDate: '01/01/2025',
  },
  {
    id: 'usr-007',
    name: 'Gabriel Siqueira',
    email: 'g.siqueira@cyber-def.com',
    role: 'User',
    status: 'OFFLINE',
    region: 'Distrito Norte',
    bio: 'Operador de segurança física e monitoramento de controles de acesso corporativo.',
    specialties: ['Physical Security', 'Access Telemetry', 'IoT Sensors'],
    reputationScore: 84,
    contributionsCount: 14,
    verifiedAlertsCount: 11,
    joinedDate: '28/07/2025',
  },
  {
    id: 'usr-008',
    name: 'Thiago Moura',
    email: 't.moura@industry-sec.br',
    role: 'Contributor',
    status: 'ONLINE',
    region: 'Distrito Industrial',
    bio: 'Especialista em segurança de redes operacionais (OT), protocolos Modbus e telemetria IoT.',
    specialties: ['OT Systems', 'Modbus/SCADA', 'Industrial IoT'],
    reputationScore: 89,
    contributionsCount: 27,
    verifiedAlertsCount: 22,
    joinedDate: '10/08/2025',
  },
  {
    id: 'usr-009',
    name: 'Valeria Santos',
    email: 'v.santos@sycron.net',
    role: 'Administrator',
    status: 'ONLINE',
    region: 'Central de Operações',
    bio: 'Administradora de infraestrutura de chave pública, RBAC e governança de dados da rede SYCRON.',
    specialties: ['PKI Infrastructure', 'Zero-Trust Architecture', 'RBAC Security'],
    reputationScore: 100,
    contributionsCount: 210,
    verifiedAlertsCount: 120,
    joinedDate: '01/01/2025',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLog[] = [
  {
    id: 'aud-001',
    userId: 'usr-syc-001',
    userName: 'Marcus Vance',
    userRole: 'Analyst',
    action: 'CREATE_NODE',
    details: 'Bloco de inteligência criado: NÚCLEO REGIONAL: Eixo Paulista (REGION)',
    timestamp: '19/08/2026 05:14:02',
    ip: '177.18.204.12',
    hash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    status: 'SUCCESS',
  },
  {
    id: 'aud-002',
    userId: 'usr-006',
    userName: 'Felipe Duarte',
    userRole: 'Moderator',
    action: 'VERIFY_ALERT',
    details: 'Validação e promoção de status de prioridade crítica para o alerta ALT-001',
    timestamp: '19/08/2026 05:08:19',
    ip: '189.40.112.88',
    hash: '8f434346648f6b96df89dda901c5176b10a6d83961dd3c1ac88b59b2dc327aa4',
    status: 'SUCCESS',
  },
  {
    id: 'aud-003',
    userId: 'usr-syc-001',
    userName: 'Marcus Vance',
    userRole: 'Analyst',
    action: 'CONNECT_NODES',
    details: 'Link estabelecido na teia: node-root-01 <-> node-alert-01',
    timestamp: '19/08/2026 05:02:11',
    ip: '177.18.204.12',
    hash: 'a665a45920422f9d417e4867efdc4fb8a04a1f3fff1fa07e998e86f7f7a27ae3',
    status: 'SUCCESS',
  },
  {
    id: 'aud-004',
    userId: 'usr-003',
    userName: 'Alexandre Prado',
    userRole: 'Analyst',
    action: 'UPLOAD_EVIDENCE',
    details: 'Arquivo de evidência auth_failure_dump.log (8.7MB) anexado ao nó node-alert-01',
    timestamp: '19/08/2026 04:55:40',
    ip: '200.144.18.9',
    hash: '2c26b46b68ffc68ff99b453c1d30413413422d706483bfa0f98a5e886266e7ae',
    status: 'SUCCESS',
  },
  {
    id: 'aud-005',
    userId: 'usr-007',
    userName: 'Gabriel Siqueira',
    userRole: 'User',
    action: 'FLAG_CONTENT',
    details: 'Disputa de veracidade de alerta ALT-004 aberta com revisão pendente',
    timestamp: '19/08/2026 04:12:05',
    ip: '179.124.99.14',
    hash: 'fcde2b2edba56bf408601fb721fe9b5c338d10ee429ea04fae5511b68fbf8fb9',
    status: 'WARNING',
  },
  {
    id: 'aud-006',
    userId: 'usr-009',
    userName: 'Valeria Santos',
    userRole: 'Administrator',
    action: 'ROTATE_API_CREDENTIALS',
    details: 'Chave de produção Gateway API v2 rotacionada via painel administrativo',
    timestamp: '19/08/2026 03:00:00',
    ip: '187.60.210.4',
    hash: '3f59e9c93a8ff247343e09d16a5dcfa91666e6fa5055b40cf988894ec0902996',
    status: 'SUCCESS',
  },
];

export const INITIAL_REPORTS: IntelligenceReport[] = [
  {
    id: 'rep-001',
    title: 'Relatório Executivo de Incidentes — Agosto 2026',
    period: '01/08/2026 a 19/08/2026',
    region: 'Todas as Regiões',
    type: 'INCIDENT_SUMMARY',
    summary: 'Consolidação de 47 incidentes catalogados na rede. 82% mitigados com sucesso pela rede colaborativa.',
    generatedAt: '19/08/2026 04:00',
    generatedBy: 'Marcus Vance',
    generatedByRole: 'Analyst',
    incidentsCount: 47,
    criticalCount: 14,
    mitigatedCount: 39,
    fileSize: '4.8 MB',
    hash: 'e892c9f91a27b84cf299602bca88172901a1820491823901429812903829012a',
  },
  {
    id: 'rep-002',
    title: 'Análise de Atividade e Dinâmica da Teia de Inteligência',
    period: 'Últimos 7 dias',
    region: 'Setor Central & Paulista',
    type: 'NETWORK_ACTIVITY',
    summary: 'Mapeamento de 284 correlações de dados entre nós de alertas e evidências em telecomunicações.',
    generatedAt: '18/08/2026 18:30',
    generatedBy: 'Dra. Helena Rossi',
    generatedByRole: 'Analyst',
    incidentsCount: 29,
    criticalCount: 8,
    mitigatedCount: 24,
    fileSize: '6.2 MB',
    hash: '1289ae8192a0149021849012a981029481902481902849012849012849012849',
  },
  {
    id: 'rep-003',
    title: 'Evolução de Vetores de Ameaça e Infraestruturas C2',
    period: 'Julho — Agosto 2026',
    region: 'Gateway Internacional',
    type: 'THREAT_EVOLUTION',
    summary: 'Estudo aprofundado sobre migração de canais de exfiltração para túneis DNS criptografados e TLS autoassinados.',
    generatedAt: '15/08/2026 11:15',
    generatedBy: 'Rafael Tavares',
    generatedByRole: 'Analyst',
    incidentsCount: 33,
    criticalCount: 11,
    mitigatedCount: 28,
    fileSize: '8.1 MB',
    hash: 'a902184091284901284901284901284901284901284901284901284901284901',
  },
];

export const INITIAL_NOTIFICATIONS: NotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Alerta Crítico Detectado',
    message: 'Tentativa massiva de Credential Stuffing em VPN Gateway na sua região (Av. Paulista).',
    type: 'ALERT',
    timestamp: '19/08 04:12',
    read: false,
    linkTab: 'alerts',
    targetId: 'alt-001',
    priority: 'CRITICAL',
  },
  {
    id: 'notif-2',
    title: 'Informação Conectada à sua Teia',
    message: 'Dra. Helena Rossi adicionou telemetria de DNS vinculada ao seu bloco de monitoramento.',
    type: 'NETWORK',
    timestamp: '19/08 04:41',
    read: false,
    linkTab: 'network',
    targetId: 'node-info-01',
    priority: 'HIGH',
  },
  {
    id: 'notif-3',
    title: 'Nova Notícia de Inteligência',
    message: 'Vazamento de Hashes NTLM Detectado no canal de Darkweb.',
    type: 'NEWS',
    timestamp: '19/08 02:40',
    read: true,
    linkTab: 'news',
    targetId: 'news-001',
    priority: 'HIGH',
  },
  {
    id: 'notif-4',
    title: 'Assinatura Ativa: SYCRON PRO',
    message: 'Seu plano PRO está com renovação programada para 25/09/2026.',
    type: 'SUBSCRIPTION',
    timestamp: '18/08 12:00',
    read: true,
    linkTab: 'subscription',
  },
  {
    id: 'notif-5',
    title: 'Relatório Executivo Pronto',
    message: 'O relatório consolidado de incidentes de Agosto 2026 foi gerado com sucesso.',
    type: 'REPORT',
    timestamp: '18/08 04:00',
    read: true,
    linkTab: 'reports',
    targetId: 'rep-001',
  },
];
